// autogenerated turbo fused MMA instance for asymmetric GGML_TYPE_Q8_0 K / GGML_TYPE_Q8_0 V
// (q8_0 K in original domain, no WHT rotation)

#include "../fattn-mma-f16.cuh"
#include "../fattn-mma-turbo.cuh"

DECL_FATTN_MMA_TURBO_CASE(256, 256, 4, 4, GGML_TYPE_Q8_0, GGML_TYPE_Q8_0);
